// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nyfekrywdzxbxbcqnsji.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im55ZmVrcnl3ZHp4YnhiY3Fuc2ppIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwMTYyODYsImV4cCI6MjA2NzU5MjI4Nn0.r6BMeKllPRWdi7ri2ZOwfOChBvgchpe_yTreotSdpq0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});